
# json地址
file:
  temp: D:/WorkStation/temp/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useSSL=true
# thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    mode: HTML
    content-type: text/html

# 表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**

  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# 加入所有静态资源路径（覆盖默认配置）
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.temp}
server:
  port: 80

